_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: CascadeROIHeads
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
  FPN:
    NORM: "SyncBN"
  BACKBONE:
    NAME: "build_resnet_bifpn_backbone"
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  STEPS: (120000, 160000)
  MAX_ITER: 180000